kind: pipeline
name: default

steps:
  - name: format
    image: rust:1
    commands:
      - rustup component add rustfmt
      - cargo fmt --check

  - name: test
    image: rust:1
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all