[package]
name = "services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
external-services={path="../external-services"}
anyhow = "1.0.71"
hound = "3.5.0"
dft = "0.5.5"
rustfft = "6.1.0"
