[package]
name = "external-services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
persistence={path="../persistence"}
hound = "3.5.0"
thiserror = "1.0.40"
